sudo: required
dist: trusty
before_install:
  - gem install bundler -v '< 2'
rvm:
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - 2.1.10
  - jruby-9.1.15.0
gemfile:
  - Gemfile
  - spec/gemfiles/i18n_0.7.gemfile
  - spec/gemfiles/i18n_0.8.gemfile
  - spec/gemfiles/i18n_0.9.gemfile
  - spec/gemfiles/i18n_1.0.gemfile
notifications:
  slack:
    secure: JryUWfe2JR0cfNT+TIHwryy8NS8m9/hbRhg+5UqwuYWuEp6gtcWCA05wKsajQyRrGaNGYKu81RA9jpQrirgQWzDUJl5o3sEWbqKZv3pW0ybn8Tx52N1mxW3Puar5KLZ8TPRphKKIJ8/1EhAh4zpC5Mtxv8Sz1/AHuqnlu6l+bb4=
