sudo: false

before_install:
  - gem install bundler -v 1.13.0.rc2

install:
  - bundle install --jobs=3 --retry=3

matrix:
  include:
     - rvm: 2.0.0
     - rvm: 2.1.10
     - rvm: 2.2.5
     - rvm: 2.3.1
     - rvm: jruby-9.1.2.0
       env: JRUBY_OPTS='--dev'
       jdk: oraclejdk8

notifications:
  slack:
    secure: JryUWfe2JR0cfNT+TIHwryy8NS8m9/hbRhg+5UqwuYWuEp6gtcWCA05wKsajQyRrGaNGYKu81RA9jpQrirgQWzDUJl5o3sEWbqKZv3pW0ybn8Tx52N1mxW3Puar5KLZ8TPRphKKIJ8/1EhAh4zpC5Mtxv8Sz1/AHuqnlu6l+bb4=
