before_install:
  - gem install bundler
  - gem update bundler
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-9.1.2.0
notifications:
  slack:
    secure: JryUWfe2JR0cfNT+TIHwryy8NS8m9/hbRhg+5UqwuYWuEp6gtcWCA05wKsajQyRrGaNGYKu81RA9jpQrirgQWzDUJl5o3sEWbqKZv3pW0ybn8Tx52N1mxW3Puar5KLZ8TPRphKKIJ8/1EhAh4zpC5Mtxv8Sz1/AHuqnlu6l+bb4=
